FROM resin/%%RESIN_MACHINE_NAME%%-node:6

ENV INITSYSTEM on

WORKDIR /usr/src/app

COPY package.json .

RUN JOBS=MAX npm install --unsafe-perm --production && npm cache clean

COPY . ./

RUN JOBS=MAX npm install --unsafe-perm && npm run build && npm prune --production && npm cache clean

CMD npm start
